# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-4181-coding/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7k325tffg900-2
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_vhdl -lib grlib {
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/grlib/stdlib/config_types.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/designs/leon5-xilinx-kc705/grlib_config_leon5.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/grlib/stdlib/version.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/grlib/stdlib/stdlib.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/grlib/amba/amba.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/grlib/amba/devices.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/grlib/amba/ahbctrl.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/grlib/dftlib/dftlib.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/grlib/amba/ahbmst.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/grlib/amba/apbctrl.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/grlib/amba/apbctrlx.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/grlib/sparc/sparc.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/grlib/modgen/leaves.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/grlib/modgen/multlib.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/grlib/dftlib/trstmux.vhd
    }
      rt::read_vhdl -lib techmap {
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/gencomp/gencomp.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/alltech/allclkgen.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/alltech/allddr.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/alltech/allmem.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/alltech/allmul.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/alltech/allpads.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/alltech/alltap.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/unisim/buffer_unisim.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/maps/cdcbus.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/maps/clkand.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/maps/clkgen.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/unisim/clkgen_unisim.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/maps/clkmux.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/maps/clkpad_ds.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/inferred/ddr_inferred.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/maps/ddr_oreg.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/unisim/ddr_unisim.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/maps/grgates.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/maps/inpad.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/maps/iopad.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/inferred/memory_inferred.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/unisim/memory_kintex7.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/unisim/memory_ultrascale.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/unisim/memory_unisim.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/maps/memrwcol.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/inferred/mul_inferred.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/maps/odpad.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/maps/outpad.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/unisim/pads_unisim.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/maps/syncram.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/maps/syncram64.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/maps/syncram_2p.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/maps/syncram_dp.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/maps/syncrambw.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/maps/syncreg.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/maps/tap.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/unisim/tap_unisim.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/maps/techbuf.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/techmap/maps/techmult.vhd
    }
      rt::read_vhdl -lib gaisler {
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/axi/axi.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/axi/ahb2axi4b.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/misc/misc.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/ddr/ahb2axi_mig_7series.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/axi/ahb2axib.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/jtag/libjtagcom.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/jtag/jtag.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/jtag/ahbjtag.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/misc/ahbram.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/misc/ahbstat.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/uart/uart.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/uart/libdcom.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/uart/ahbuart.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/uart/apbuart.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/arith/arith.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/ddr/axi_mig_7series.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/leon5/leon5.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/leon5v0/leon5int.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/leon5v0/bht_pap.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/leon5v0/btb.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/leon3/leon3.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/leon5v0/cachemem5.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/leon5v0/cctrl5.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/leon5v0/cpucore5.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/leon5v0/dbgmod5.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/uart/dcom.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/uart/dcom_uart.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/arith/div32.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/net/net.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/greth/ethernet_mac.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/misc/gptimer.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/greth/greth_gbit_mb.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/greth/greth_mb.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/greth/grethm_mb.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/i2c/i2c.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/i2c/i2cmst.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/leon5v0/irqmp5.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/leon5v0/itbufmem5.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/leon5v0/iu5.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/jtag/jtagcom.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/jtag/jtagcom2.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/l2cache/pkg/l2cache.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/leon5v0/l5stat.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/memctrl/memctrl.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/spi/spi.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/subsys/subsys.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/leon5v0/leon5sys.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/arith/mul32.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/leon5v0/nanofpu.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/leon5v0/regfile5_dff.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/leon5v0/regfile5_ram.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/greth/adapters/rgmii_kc705.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/misc/rstgen.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/memctrl/sdmctrl.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/spi/spimctrl.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/gaisler/leon5v0/tbufmem5.vhd
    }
      rt::read_vhdl -lib work {
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/designs/leon5-xilinx-kc705/ahbrom.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/designs/leon5-xilinx-kc705/config.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/designs/leon5-xilinx-kc705/ddr_dummy.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/designs/leon5-xilinx-kc705/leon5mp.vhd
    }
      rt::read_vhdl -lib eth {
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/eth/core/greth_pkg.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/eth/core/eth_ahb_mst.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/eth/core/eth_edcl_ahb_mst.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/eth/core/eth_rstgen.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/eth/comp/ethcomp.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/eth/core/greth_rx.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/eth/core/greth_tx.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/eth/core/grethc.vhd
    }
      rt::read_vhdl -lib opencores {
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/opencores/i2c/i2c_master_bit_ctrl.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/opencores/i2c/i2c_master_byte_ctrl.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/opencores/i2c/i2coc.vhd
    }
      rt::read_vhdl -lib esa {
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/esa/memoryctrl/memoryctrl.vhd
      /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/lib/esa/memoryctrl/mctrl.vhd
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top leon5mp
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-4181-coding/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
