# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/zhichao/Downloads/GRLIB/grlib-gpl-2022.4-b4280/boards/xilinx-kc705-xc7k325t/xilinx-kc705-xc7k325t.xdc

# IP: ip/mig/mig.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mig || ORIG_REF_NAME==mig} -quiet] -quiet

# XDC: ip/mig/mig/user_design/constraints/mig_ooc.xdc

# XDC: ip/mig/mig/user_design/constraints/mig.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mig || ORIG_REF_NAME==mig} -quiet] -quiet
